language: java
jdk:
  - oraclejdk8
  
notifications:
  email:
    recipients:
      - uo231096@uniovi.es
    on_success: never
    on_failure: always
  
before_install:
  - pip install --user codecov
  - pip install codecov

after_success:
  - codecov
